// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9_LUs0XcvqwdBjAtt2SklVettCAYt9sY',
    appId: '1:801564809240:web:a2f0c7bafbb29451d84b6d',
    messagingSenderId: '801564809240',
    projectId: 'iam-recette-app',
    authDomain: 'iam-recette-app.firebaseapp.com',
    storageBucket: 'iam-recette-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGoAcdgnywaRKuRfs34NS_RelRlJD-xEw',
    appId: '1:801564809240:android:fe7c15fdf11a7483d84b6d',
    messagingSenderId: '801564809240',
    projectId: 'iam-recette-app',
    storageBucket: 'iam-recette-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlz4_3M_7XHUlLsI1V5rKpSbMrLdRcjpw',
    appId: '1:801564809240:ios:4030b32de56d77bad84b6d',
    messagingSenderId: '801564809240',
    projectId: 'iam-recette-app',
    storageBucket: 'iam-recette-app.appspot.com',
    iosBundleId: 'com.example.iamAppRecette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlz4_3M_7XHUlLsI1V5rKpSbMrLdRcjpw',
    appId: '1:801564809240:ios:004955256228ec67d84b6d',
    messagingSenderId: '801564809240',
    projectId: 'iam-recette-app',
    storageBucket: 'iam-recette-app.appspot.com',
    iosBundleId: 'com.example.iamAppRecette.RunnerTests',
  );
}
